@authToken = {{gerar_token_jwt.response.body.token}}


# @name gerar_token_jwt
POST http://localhost:5000/


###

POST http://localhost:5000/validate
Authorization: Bearer {{authToken}}


###

# @name first_method
GET http://localhost:5000/


###

# @name add_account
POST http://localhost:5000/bank/registry
Content-Type: application/json

{
  "username": "mark",
  "password": "123456"
}

###

# @name account_login
POST http://localhost:5000/bank/login
Content-Type: application/json

{
  "username": "mark",
  "password": "123456"
}